# .github/release.yml

changelog:
  categories:
    - title: Changelog
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: Dependencies
      labels:
        - dependencies
